# Generated by Django 4.2.29 on 2026-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_add_rejected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
