# Generated by Django 4.2.29 on 2026-06-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_add_admin_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='evidence_image',
        ),
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='complaints.complaint')),
            ],
        ),
    ]
