# Generated by Django 4.2.29 on 2026-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_add_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='tracking_id',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
    ]
